const defaultExitRules = [
  {
    id: "stop-on-reply",
    title: "Stop on reply",
    description: "Exits a contact from the sequence if they reply to any message.",
  },
  {
    id: "stop-on-bounce",
    title: "Stop on bounce",
    description: "Exits a contact if any email bounces.",
  },
  {
    id: "stop-on-unsubscribe",
    title: "Stop on unsubscribe",
    description: "Exits a contact if they unsubscribe from any email.",
  },
]

export const templateCategories = [
  { id: "marketing", label: "Marketing", count: 4 },
  { id: "sales", label: "Sales", count: 4 },
  { id: "re-engagement", label: "Re-engagement", count: 3 },
  { id: "events", label: "Events", count: 3 },
  { id: "blank", label: "Blank", count: 1 },
]

export const sequenceTemplates = [
  {
    id: "enterprise-intro",
    name: "Enterprise Intro Sequence",
    category: "marketing",
    description: "Introduce RC Sales and qualify interest in SAP migration services for enterprises.",
    previewDescription:
      "Introduce RC Sales, communicate our SAP migration expertise, and qualify interest with a clear value proposition.",
    metadata: ["6 Steps", "12–16 Days", "Best for cold leads"],
    steps: [
      { day: "Day 1", title: "Welcome & Introduction", channel: "Email" },
      { day: "Day 3", title: "Pain & Priorities Check", channel: "Email" },
      { day: "Day 6", title: "Value & Case Study", channel: "Email" },
      { day: "Day 10", title: "Resource: SAP Migration Guide", channel: "Email" },
      { day: "Day 13", title: "Invitation to Connect", channel: "Email" },
      { day: "Day 16", title: "Final Check-in", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "value-led-follow-up",
    name: "Value-led Follow-up Sequence",
    category: "marketing",
    description: "Share customer value, insights, and social proof to nurture and build trust.",
    previewDescription:
      "Share business outcomes, proof points, and useful insights before asking for a deeper conversation.",
    metadata: ["5 Steps", "10–14 Days", "Best for warm leads"],
    steps: [
      { day: "Day 1", title: "Value Recap", channel: "Email" },
      { day: "Day 3", title: "Customer Proof", channel: "Email" },
      { day: "Day 7", title: "Insight Follow-up", channel: "Email" },
      { day: "Day 10", title: "ROI Angle", channel: "Email" },
      { day: "Day 14", title: "Next Step Ask", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "marketing-re-engagement",
    name: "Re-engagement Sequence",
    category: "marketing",
    description: "Reconnect with inactive prospects and revive conversations.",
    previewDescription:
      "Use a concise value-driven check-in to reopen conversations with inactive SAP migration prospects.",
    metadata: ["4 Steps", "8–12 Days", "Best for inactive leads"],
    steps: [
      { day: "Day 1", title: "Friendly Check-in", channel: "Email" },
      { day: "Day 4", title: "New Value Resource", channel: "Email" },
      { day: "Day 8", title: "Relevant Trigger", channel: "Email" },
      { day: "Day 12", title: "Close the Loop", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "meeting-request",
    name: "Meeting Request Sequence",
    category: "marketing",
    description: "Drive prospects to book a meeting with clear, low-friction asks.",
    previewDescription:
      "Convert qualified interest into a meeting with direct, useful asks and minimal friction.",
    metadata: ["5 Steps", "9–13 Days", "Best for qualified leads"],
    steps: [
      { day: "Day 1", title: "Context & Meeting Ask", channel: "Email" },
      { day: "Day 3", title: "Business Reason", channel: "Email" },
      { day: "Day 6", title: "Calendar Nudge", channel: "Email" },
      { day: "Day 10", title: "Decision Support", channel: "Email" },
      { day: "Day 13", title: "Final Scheduling Ask", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "sales-discovery",
    name: "Sales Discovery Sequence",
    category: "sales",
    description: "Qualify pains, priorities, and decision criteria for enterprise opportunities.",
    previewDescription: "Open consultative discovery with clear questions and relevant SAP migration context.",
    metadata: ["5 Steps", "10 Days", "Best for sales discovery"],
    steps: [
      { day: "Day 1", title: "Discovery Opener", channel: "Email" },
      { day: "Day 3", title: "Priority Question", channel: "Email" },
      { day: "Day 6", title: "Stakeholder Check", channel: "Email" },
      { day: "Day 8", title: "Use Case Prompt", channel: "Email" },
      { day: "Day 10", title: "Discovery Close", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "demo-follow-up",
    name: "Demo Follow-up Sequence",
    category: "sales",
    description: "Follow up after demos with value recap, objections, and next steps.",
    previewDescription: "Keep momentum after a demo with recap, proof, and a clear next-step path.",
    metadata: ["4 Steps", "7 Days", "Best after demos"],
    steps: [
      { day: "Day 1", title: "Demo Recap", channel: "Email" },
      { day: "Day 2", title: "Value Summary", channel: "Email" },
      { day: "Day 5", title: "Objection Check", channel: "Email" },
      { day: "Day 7", title: "Next Step", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "proposal-follow-up",
    name: "Proposal Follow-up Sequence",
    category: "sales",
    description: "Keep proposal conversations moving without adding pressure.",
    previewDescription: "Guide stakeholders from proposal review to decision with concise follow-ups.",
    metadata: ["4 Steps", "12 Days", "Best for proposals"],
    steps: [
      { day: "Day 1", title: "Proposal Sent", channel: "Email" },
      { day: "Day 4", title: "Questions Check", channel: "Email" },
      { day: "Day 8", title: "Decision Criteria", channel: "Email" },
      { day: "Day 12", title: "Close Next Step", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "decision-maker",
    name: "Decision Maker Sequence",
    category: "sales",
    description: "Reach senior stakeholders with outcome-focused messaging.",
    previewDescription: "Connect with decision makers around risk, ROI, and business outcomes.",
    metadata: ["5 Steps", "15 Days", "Best for executives"],
    steps: [
      { day: "Day 1", title: "Executive Opener", channel: "Email" },
      { day: "Day 4", title: "Risk Angle", channel: "Email" },
      { day: "Day 8", title: "Outcome Proof", channel: "Email" },
      { day: "Day 12", title: "Stakeholder Alignment", channel: "Email" },
      { day: "Day 15", title: "Executive Close", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "cold-lead-winback",
    name: "Cold Lead Winback",
    category: "re-engagement",
    description: "Restart conversations with leads who have gone quiet.",
    previewDescription: "Use useful context and a lightweight question to win back cold leads.",
    metadata: ["3 Steps", "9 Days", "Best for cold leads"],
    steps: [
      { day: "Day 1", title: "New Context", channel: "Email" },
      { day: "Day 5", title: "Relevant Resource", channel: "Email" },
      { day: "Day 9", title: "Final Check", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "dormant-opportunity",
    name: "Dormant Opportunity",
    category: "re-engagement",
    description: "Revisit older opportunities with updated business value.",
    previewDescription: "Reopen dormant opportunities by sharing what has changed and why it matters now.",
    metadata: ["4 Steps", "14 Days", "Best for stalled deals"],
    steps: [
      { day: "Day 1", title: "Opportunity Reopen", channel: "Email" },
      { day: "Day 4", title: "Updated Value", channel: "Email" },
      { day: "Day 9", title: "Priority Check", channel: "Email" },
      { day: "Day 14", title: "Close Loop", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "renewal-check-in",
    name: "Renewal Check-in",
    category: "re-engagement",
    description: "Reconnect around renewals, expansion, or optimization opportunities.",
    previewDescription: "Prompt renewal and optimization discussions with practical SAP migration guidance.",
    metadata: ["3 Steps", "10 Days", "Best for existing accounts"],
    steps: [
      { day: "Day 1", title: "Renewal Context", channel: "Email" },
      { day: "Day 5", title: "Optimization Idea", channel: "Email" },
      { day: "Day 10", title: "Planning Ask", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "webinar-invite",
    name: "Webinar Invite Sequence",
    category: "events",
    description: "Invite prospects to a webinar with clear value and reminders.",
    previewDescription: "Drive registration and attendance for SAP migration webinars.",
    metadata: ["4 Steps", "10 Days", "Best for webinars"],
    steps: [
      { day: "Day 1", title: "Webinar Invite", channel: "Email" },
      { day: "Day 4", title: "Agenda Highlight", channel: "Email" },
      { day: "Day 8", title: "Reminder", channel: "Email" },
      { day: "Day 10", title: "Final Reminder", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "event-follow-up",
    name: "Event Follow-up Sequence",
    category: "events",
    description: "Follow up after events with resources, recap, and meeting asks.",
    previewDescription: "Turn event engagement into qualified conversations.",
    metadata: ["4 Steps", "8 Days", "Best after events"],
    steps: [
      { day: "Day 1", title: "Thanks & Recap", channel: "Email" },
      { day: "Day 3", title: "Resource Share", channel: "Email" },
      { day: "Day 6", title: "Business Prompt", channel: "Email" },
      { day: "Day 8", title: "Meeting Ask", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "conference-outreach",
    name: "Conference Outreach Sequence",
    category: "events",
    description: "Reach prospects before and after conferences with timely messaging.",
    previewDescription: "Coordinate pre-event outreach and post-event follow-up in one sequence.",
    metadata: ["5 Steps", "16 Days", "Best for conferences"],
    steps: [
      { day: "Day 1", title: "Pre-event Intro", channel: "Email" },
      { day: "Day 5", title: "Meet at Event", channel: "Email" },
      { day: "Day 9", title: "Event Reminder", channel: "Email" },
      { day: "Day 13", title: "Post-event Recap", channel: "Email" },
      { day: "Day 16", title: "Next Conversation", channel: "Email" },
    ],
    exitRules: defaultExitRules,
  },
  {
    id: "blank-sequence",
    name: "Blank Sequence",
    category: "blank",
    description: "Start from a clean sequence and add each step manually.",
    previewDescription: "Build a custom email sequence from scratch.",
    metadata: ["0 Steps", "Custom timing", "Best for custom plays"],
    steps: [],
    exitRules: defaultExitRules,
  },
]

export const blankSequenceTemplate = sequenceTemplates.find((template) => template.id === "blank-sequence")
